working_directory = "None"

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
# black = "#18100e"
black = "#303030"
blue = "#e8b270"
cyan = "#c25028"
green = "#40251e"
magenta = "#665048"
red = "#ae303a"
white = "#a878fd"
yellow = "#ffeed4"

[colors.cursor]
cursor = "#ffffff"
text = "#181818"

[colors.normal]
black = "#170f0d"
blue = "#a62e38"
cyan = "#3ea0e8"
green = "#d85830"
magenta = "#6b3827"
red = "#584bbb"
white = "#9890a8"
yellow = "#d85830"

[colors.primary]
background = "#170e0a"
foreground = "#ffffff"

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.bold]
# family = "RobotoMonoNerdFont"
family = "Scientifica"
style = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "RobotoMonoNerdFont"
family = "Scientifica"
style = "Thin"

[font.normal]
# family = "RobotoMonoNerdFont"
family = "Scientifica"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mods = "Alt"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0
