working_directory = "None"

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

#[colors.cursor]
#cursor = '#c0caf5'
#text = '#1a1b26'

# Normal colors
[colors.normal]
black = '#15161e'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#a9b1d6'

# Bright colors
[colors.bright]
black = '#414868'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#bb9af7'
cyan = '#7dcfff'
white = '#c0caf5'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#ff9e64'

[[colors.indexed_colors]]
index = 17
color = '#db4b4b'

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.glyph_offset]
x = 0
y = 0

[font.bold]
# family = "RobotoMonoNerdFont"
# family = "IBMPlexMono"
family = "Scientifica"
# family = "BigBlueTermPlusNerdFontMono"
# family = "BigBlueTermPlusNerdFontMono"
style = "Regular"

[font.italic]
# family = "RobotoMonoNerdFont"
# family = "IBMPlexMono"
family = "Scientifica"
# family = "BigBlueTermPlusNerdFontMono"
style = "Regular"

[font.normal]
# family = "RobotoMonoNerdFont"
# family = "Scientifica"
family = "Scientifica"
# family = "IBMPlexMono"
# family = "BigBlueTermPlusNerdFontMono"
# family = "BigBlueTermPlusNerdFont"
# family = "BigBlueTermPlusNerdFont"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "K"
mods = "Alt"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/bin/zsh"

[window]
decorations = "none"

[window.padding]
x = 0
y = 0
